[tool.poetry]
name = "io"
version = "0.1.0"
description = "Handle IO operations for Oktoberfest"
authors = ["WassimG <wassim.gabriel@tum.de>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.0"
pandas = "^1.3.0"
h5py = "^3.3.0"
fundamentals = {git = "git@gitlab.lrz.de:compmass/prosit/tools/fundamentals.git", branch="develop"}
pymzml = "^2.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
